[project]
name = "gcalender-mcp"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.12"
dependencies = [
    "dotenv>=0.9.9",
    "fastmcp>=2.12.4",
    "google-auth>=2.40.3",
    "mcp>=1.14.1",
    "pyjwt>=2.10.1",
]
